# 应用名称
spring:
  application:
  name: SpringBootDemo
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdemo?charset=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    hiddenmethod:
      filter:
        enable: true

# 应用服务 web 访问端口
server:
  port: 8081

#定义变量在 java 类中获取
name: 张三
age: 22
birthday: 2000/01/01

user:
  name: 李四
  age: 21
  birthday: 2001/02/02
  #map 的使用一，放对象中读取，并通过{}里面的 key:value 方式设置，通过","设置下一组 k:v
  fruit1: { apple: 1, pear: 3 }
  #map 的使用二，放对象中读取，并通过 key:value 设置，通过换行设置下一组 k:v
  fruit2:
    arange: 2
    banana: 4
  #list 的使用一，放到对象中，使用对象接收并读取
  animals1:
    - pig
    - dog
    - cat
#list 的使用二，使用 @Value 注解，不需要放到对象中，以","分隔
animals2: tiger,cat,cow

name1: 张三
lesson1: SpringBoot
desc1: ${name1}同学正在努力学习${lesson1}#占位符

